"""
Database models module.

Defines ORM models for the BiSol application:
- User: Stores user credentials and identity
- Dashboard: Stores generated dashboard configurations
- Upload: Tracks uploaded files
- PasswordResetToken: Handles password reset workflow

These models map directly to database tables using SQLAlchemy ORM.
"""

# ---------- SQLALCHEMY CORE ----------
from sqlalchemy import (
    Column, Integer, String, JSON, ForeignKey,
    BigInteger, DateTime, Text, Boolean
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

# ---------- DATABASE BASE ----------
from database import Base


# ---------- USER MODEL ----------
class User(Base):
    """
    Represents a registered user.

    Fields:
        id (int): Primary key
        name (str): User's full name
        email (str): Unique email address
        password_hash (str): Hashed password
    """

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    email = Column(String(150), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)


# ---------- DASHBOARD MODEL ----------
class Dashboard(Base):
    """
    Stores dashboard configurations generated by users.

    Fields:
        id (int): Primary key
        user_id (int): Foreign key referencing User
        dashboard_spec (JSON): Chart configuration data
        preview_rows (JSON): Sample dataset preview
        prompt (str): User input prompt (optional)
        background_color (str): UI customization
        created_at (datetime): Creation timestamp
        updated_at (datetime): Last update timestamp

    Relationships:
        user → Associated User object
    """

    __tablename__ = "dashboards"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    dashboard_spec = Column(JSON, nullable=False)
    preview_rows = Column(JSON, nullable=False)

    prompt = Column(Text)
    background_color = Column(String(20), default="#ffffff")

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now()
    )

    # --- Relationship to User ---
    user = relationship("User", backref="dashboards")


# ---------- UPLOAD MODEL ----------
class Upload(Base):
    """
    Tracks user-uploaded files.

    Fields:
        id (int): Primary key
        user_id (int): Foreign key referencing User
        filename (str): Name of uploaded file
        file_size (int): File size in bytes
        uploaded_at (datetime): Upload timestamp
    """

    __tablename__ = "uploads"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"))
    filename = Column(String(255), nullable=False)
    file_size = Column(BigInteger, nullable=False)
    uploaded_at = Column(DateTime(timezone=True), server_default=func.now())


# ---------- PASSWORD RESET TOKEN MODEL ----------
class PasswordResetToken(Base):
    """
    Handles password reset tokens.

    Fields:
        id (int): Primary key
        user_id (int): Foreign key referencing User
        token (str): Hashed reset token
        expires_at (datetime): Expiration timestamp
        used (bool): Indicates if token has been used
        created_at (datetime): Creation timestamp
    """

    __tablename__ = "password_reset_tokens"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    token = Column(String(255), nullable=False, index=True)
    expires_at = Column(DateTime, nullable=False)

    used = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())